default_stages: [commit]

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [
#          "--strict",
          "--namespace-packages",
          "--ignore-missing-imports",
          "--show-error-codes"
        ]
        additional_dependencies:
          - types-PyYAML
          - types-aiofiles
          - types-beautifulsoup4
          - types-boto
          - types-protobuf
          - types-pytz
          - types-requests
          - types-setuptools
          - types-six
          - types-tabulate
#          - git+https://github.com/Rapptz/discord.py
#          - discord-ext-menus
#          - tortoise-orm
          - sympy


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.285
    hooks:
      - id: ruff

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
