version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  tuxbot:
    build:
      context: .
      dockerfile: ./compose/local/tuxbot/Dockerfile
    image: tuxbot_bot_local_tuxbot
    container_name: tuxbot
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.tuxbot
      - ./.envs/.local/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: tuxbot_bot_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres