version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  tuxbot:
    build:
      context: .
      dockerfile: ./compose/production/tuxbot/Dockerfile
    image: tuxbot_bot_production_tuxbot
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.tuxbot
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: tuxbot_bot_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
