version: '3'

volumes:
  tuxbot_production_postgres_data: {}
  tuxbot_production_postgres_data_backups: {}

services:
  bot:
    build:
      context: .
      dockerfile: docker/production/bot/Dockerfile
    image: tuxbot_production_bot
    container_name: tuxbot_production_bot
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.bot
      - ./.envs/.production/.cogs
      - ./.envs/.production/.postgres
    user: tuxbot
    command: /start

  postgres:
    build:
      context: .
      dockerfile: docker/production/postgres/Dockerfile
    image: tuxbot_production_postgres
    container_name: tuxbot_production_postgres
    volumes:
      - tuxbot_production_postgres_data:/var/lib/postgresql/data:Z
      - tuxbot_production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:7
    container_name: tuxbot_production_redis
