name: Pre-commit

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          allow-prereleases: true
          cache: 'pip'

      - run: python -m virtualenv venv
      - run: ./venv/bin/pip install -r requirements/local.txt
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
